In [1]:
from numpy import array
M = array([[1,2,3],[4,5,6]])

In [2]:
print(M)

[[1 2 3]
 [4 5 6]]


In [7]:
from numpy import matmul
A = array([[1,-1,0],[-1,2,-1],[0,-1,1]])
B = array([[0,0,1],[0,2,0],[3,0,0]])
print('AB=')
print(matmul(A,B))
print('BA=')
print(matmul(B,A))

AB=
[[ 0 -2  1]
 [-3  4 -1]
 [ 3 -2  0]]
BA=
[[ 0 -1  1]
 [-2  4 -2]
 [ 3 -3  0]]


In [4]:
from numpy.linalg import eig
A = array([[5/4,0],[0,3/4]])
w,v = eig(A)
print('First  pair:',w[0], v[:,0])
print('Second pair:',w[1], v[:,1])

First  pair: 1.25 [1. 0.]
Second pair: 0.75 [0. 1.]


In [5]:
print(matmul(A,v[:,0]))
print(w[0]*v[:,0])

[1.25 0.  ]
[1.25 0.  ]


In [6]:
print(matmul(A,v[:,1]))
print(w[1]*v[:,1])

[0.   0.75]
[0.   0.75]
