The solution to the Heat Equation used a difference equation to generate a sequence of solutions stepping forward in time, $T_{k+1}=MT_k$. We expect a steady-state solution $$T_{\infty}=\lim_{k\longrightarrow\infty}T_k where T_{\infty}=MT_{\infty}.$$

Many processes can be modeled in a similar way, including stochastic processes and statistical physics, where the difference equation creates a Markov chain. See https://www.math.wustl.edu/~feres/HotLasers.pdf Links to an external site.

Here, we will model how cars move between three cities using a Markov approach.

A car rental company has three locations, P Q R. A car rented from one location can be returned to any other location. In the past, each week, p cars are rented from location P, and a fraction are returned to each location. We can make this list showing how cars rented each week are redistributed:
<pre>
p cars rented from P: 60% return to P, 30% returned to Q, 10% returned to R.
q cars rented from Q: 10% return to P, 80% returned to Q, 10% returned to R.
r cars rented from R: 10% return to P, 20% are returned to Q, 70% returned to R.
</pre>

1) Let $p_k, q_k, r_k$ be the number of cars at each location on week k. Write down 3 equations for  $p_{k+1}, q_{k+1}, r_{k+1}$using the redistributions above.

2) Define the column vector $x_k=\left[p_k,q_k,r_k\right]^{T}$ giving the cars at each location on week k. Write a matrix equation for  using a matrix M

3) Write a python program to find $x_k$ for 10 weeks. Start with 200 cars in each city ($x_o=[200,200,200]^{T}$). Does the sequence converge? What is the limiting value $x_{\infty}$? Does the starting distribution matter after enough weeks?

4) Note that $x_{\infty}=Mx_{\infty}$ so that $x_{\infty}$ is an eigenvector of M with eigenvalue $\lambda=1$. Use [numpy.linalg.eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html) to find $x_{\infty}$. Note that eig returns a unit vector; how do you find $x_{\infty}$ from this unit vector and 



## Matrix Representation of the Car Rental Process

To model the car rental process using a matrix, we can define a transition matrix `M` that represents the probabilities of cars being returned to each location. The matrix `M` will be defined as follows:

$$
M = \begin{bmatrix}
0.6 & 0.1 & 0.1 \\
0.3 & 0.8 & 0.2 \\
0.1 & 0.1 & 0.7
\end{bmatrix}
$$

Where:
- The first row represents the probabilities of cars returned to location P from P, Q, and R respectively.
- The second row represents the probabilities of cars returned to location Q from P, Q, and R respectively.
- The third row represents the probabilities of cars returned to location R from P, Q, and R respectively.

Using this matrix, we can express the state of the system at week `k` as a vector $`x_k = \begin{bmatrix} p_k \\ q_k \\ r_k \end{bmatrix}`$. The state at week `k+1` can then be calculated as:

$$
x_{k+1} = M x_k
$$

This allows us to model the distribution of cars across the three locations over time.

In [27]:
# Initialize the transition matrix M and the initial state vector x
import numpy as np

# Transition matrix M
M = np.array([[0.6, 0.1, 0.1],
              [0.3, 0.8, 0.2],
              [0.1, 0.1, 0.7]])

# Initial state vector x with 200 cars at each location
x_0 = np.array([200, 200, 200])

# Display the matrix and initial state
print("Transition Matrix M:\n", M)


Transition Matrix M:
 [[0.6 0.1 0.1]
 [0.3 0.8 0.2]
 [0.1 0.1 0.7]]


Create a loop and updatate x over 10 weeks.

In [28]:
x_0= np.array([600, 0, 0])
norml1 = np.linalg.norm(x_0, 1)
norm = np.linalg.norm(x_0)
norm_eu= np.sqrt(np.sum(x_0**2))
print(f"Initial state x_0: {x_0}, L1 norm: {norml1}, L2 norm: {norm}, Euclidean norm: {norm_eu}")

Initial state x_0: [600   0   0], L1 norm: 600.0, L2 norm: 600.0, Euclidean norm: 600.0


In [33]:
print("Initial State x_0:\n", x_0, 'sum=', np.sum(x_0), 'magnitude=', np.linalg.norm(x_0))  # Print the initial state, its sum, and its L1 norm
# Loop over 10 weeks
x = x_0
for week in range(20):
    # Update the state vector by multiplying with the transition matrix
    x = np.matmul(M, x)  # Matrix multiplication to get the new state
    print(f"State after week {week + 1}:\n", x, 'sum=', np.sum(x), 'magnitude=', np.linalg.norm(x))  # Print the state, its sum, and its magnitude

Initial State x_0:
 [600   0   0] sum= 600 magnitude= 600.0
State after week 1:
 [360. 180.  60.] sum= 600.0 magnitude= 406.9397989875161
State after week 2:
 [240. 264.  96.] sum= 600.0 magnitude= 369.47530364017564
State after week 3:
 [180.  302.4 117.6] sum= 600.0 magnitude= 371.0465199944611
State after week 4:
 [150.   319.44 130.56] sum= 600.0 magnitude= 376.2815796713945
State after week 5:
 [135.    326.664 138.336] sum= 600.0 magnitude= 379.56714530106535
State after week 6:
 [127.5    329.4984 143.0016] sum= 600.0 magnitude= 381.14944996040595
State after week 7:
 [123.75    330.44904 145.80096] sum= 600.0 magnitude= 381.7964778174927
State after week 8:
 [121.875    330.644424 147.480576] sum= 600.0 magnitude= 382.0075536485942
State after week 9:
 [120.9375    330.5741544 148.4883456] sum= 600.0 magnitude= 382.03918548042964
State after week 10:
 [120.46875    330.43824264 149.09300736] sum= 600.0 magnitude= 382.0090009007943
State after week 11:
 [120.234375   330.3098205

Now find the eigenvalues and eigenvectors of M to get steady state directly

In [30]:
eigvals, eigvecs = np.linalg.eig(M)
print("Eigenvalues:\n", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues:
 [1.  0.5 0.6]
Eigenvectors:
 [[-3.14269681e-01 -7.07106781e-01  1.03627506e-15]
 [-8.64241621e-01  7.07106781e-01 -7.07106781e-01]
 [-3.92837101e-01  8.15686667e-16  7.07106781e-01]]


The first column of eigvecs is the desired eigenvector, but notice it is not realistic. There is less than one car in each city! It might even be negative!

In [31]:
print(eigvecs[:,0])

[-0.31426968 -0.86424162 -0.3928371 ]


What's wrong? It's not normalized correctly. In this problem, it is the sum of the cars that is conserved, so sormalize to conserve the number of cars=600. That is, the sum of the components of the vector must add up to the number of cars.

In [32]:
norm = 600/sum(eigvecs[:,0])
print(eigvecs[:,0]*norm)

[120. 330. 150.]
