## Vectors and Matrices in Python

Vectors and Matrices are not native to python and there are various ways to work with these in numpy. Below I show some of the options and pitfalls. My preference is to make my code look as much like my math as possible, so that helps steer the choices I make.

A numpy array with n elements is basically an n-tuple and a vector in $R^n$. For many operations, this works fine. numpy includes a dot and cross product funtion to work with arrays as vectors.

Here I define two vectors as numpy arrays and take cross, dot product. Note that standard multiplication and addition operate <b>elementwise</b>.

In [23]:
from numpy import array, dot, cross

a = array([1,1,0])
b = array([0,1,1])

print('a = ',a)
print('b = ',b)
print('Multiply: ', a*b)
print('Add: ',a+b)
print('dot prod: ',dot(a,b))
print('cross prod: ', cross(a,b))

a =  [1 1 0]
b =  [0 1 1]
Multiply:  [0 1 0]
Add:  [1 2 1]
dot prod:  1
cross prod:  [ 1 -1  1]


Now we'd like to make matrices. The best way is to treat a matrix as an array of row vectors, with each row vector itself an array. That is, it is an array of arrays. You can make tensors this way too!

Adding .T to a matrix takes its transpose

Here is the 3x3 identity matrix and another 3x3 matrix:

In [24]:
M = array([[1,0,0],[0,1,0],[0,0,1]])
A = array([[1,2,3],[4,5,6],[8,8,9]])
print('A=\n',A)
print('Transpose A=\n',A.T)

print('M=\n',M)

A=
 [[1 2 3]
 [4 5 6]
 [8 8 9]]
Transpose A=
 [[1 4 8]
 [2 5 8]
 [3 6 9]]
M=
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


There are several ways to try multiplying. 

\* does elementwise like for any array. 

numpy matmul(A,B) does standard matrix multiplication

The @ operator stands in for matrix multiplication. I avoid this because it seems a bit obscure.

In [25]:
print(A*M)
print(matmul(M,A))
print(A@M)
print(A.T)

[[1 0 0]
 [0 5 0]
 [0 0 9]]
[[1 2 3]
 [4 5 6]
 [8 8 9]]
[[1 2 3]
 [4 5 6]
 [8 8 9]]
[[1 4 8]
 [2 5 8]
 [3 6 9]]


The problem is when using vectors and matrices together. We think of vectors as 1xn matrices. So the dot product is matrix multiplication with transpose: $a \cdot b = ab^T$
using the shape rule (nxm)(mxl)->(nxl)

If we use matmul naively with the arrays a and b, we get unexpected results:

In [29]:
print(matmul(a,b))
print(matmul(b,a))
print(matmul(a,b.T))
print(matmul(b.T,a))

print(matmul(a,A))
print(matmul(A,a))

1
1
1
1
[5 7 9]
[ 3  9 16]


The shape function returns the shape of an object. Note how my matrices are the expected shape but a and b have a second undefined dimension:

In [13]:
print(shape(A))
print(shape(a))

(3, 3)
(3,)


The solution is to explcitly make my vectors 1xn matrices, which gives the expected behavior:

In [30]:
a = array([[1,1,0]])
b = array([[0,1,1]])

print('a = ',a)
print('b = ',b)


print('a b.T = \n',matmul(a,b.T))
print('b.T a = \n',matmul(b.T,a))

print('a A = \n', matmul(a,A))
print('A aT = \n', matmul(A,a.T))

a =  [[1 1 0]]
b =  [[0 1 1]]
a b.T = 
 [[1]]
b.T a = 
 [[0 0 0]
 [1 1 0]
 [1 1 0]]
a A = 
 [[5 7 9]]
A aT = 
 [[ 3]
 [ 9]
 [16]]
