## Vectors and Matrices in Python

Vectors and Matrices are not native to python and there are various ways to work with these in numpy. Below I show some of the options and pitfalls. My preference is to make my code look as much like my math as possible, so that helps steer the choices I make. First we import the functions we need from numpy

In [13]:
from numpy import array, dot, cross, matmul, shape, transpose

A numpy array with n elements is basically an n-tuple and a vector in $R^n$. For many operations, this works fine. numpy includes a dot and cross product funtion to work with arrays as vectors.

Here I define two  numpy arrays a and b.

In [14]:
a = array([1,1,0])
b = array([0,1,1])

Below try different ways to multiply and add them using + * dot(a,b) and cross(a,b)

In [15]:
result = a
print(result)

[1 1 0]


Now we'd like to make matrices. The best way is to treat a matrix as an array of row vectors, with each row vector itself an array. That is, it is an array of arrays. You can make tensors this way too!

Adding .T to a matrix takes its transpose

Here is the 3x3 identity matrix and another 3x3 matrix:

In [16]:
M = array([[1,0,0],[0,1,0],[0,0,1]])
A = array([[1,2,3],[4,5,6],[8,8,9]])
print('A=\n',A)
print('Transpose A=\n',A.T)

print('M=\n',M)

A=
 [[1 2 3]
 [4 5 6]
 [8 8 9]]
Transpose A=
 [[1 4 8]
 [2 5 8]
 [3 6 9]]
M=
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


There are several ways to try multiplying. 

\* does elementwise like for any array. 

numpy matmul(A,B) does standard matrix multiplication

The @ operator stands in for matrix multiplication. I avoid this because it seems a bit obscure.

numpy matmul uses fortran code from the BLAS and LAPACK library to compute matrix multiplication very fast. You cannot do this is as fast using loops in python.  

Try these below to see what you get.

In [17]:
result = A
print(result)

[[1 2 3]
 [4 5 6]
 [8 8 9]]


The problem is when using vectors and matrices together. Above we defined 1-d arrays a and b and treated them as vectors to take the dot product. This makes sense since we think of vectors as 1xn matrices. But the dot product is also a sort of matrix multiplication with transpose: $a \cdot b = ab^T$
using the shape rule (nxm)(mxl)->(nxl)

If we do matrix operations with the arrays a and b, we get unexpected results:

In [18]:
print('b=',b)
print('b.T=', b.T)

print('a•b=', matmul(a,b))
print('b•a=', matmul(b,a))
print('a•b.T=', matmul(a,b.T))
print('b.T•a=', matmul(b.T,a))

print('aA=', matmul(a,A))
print('Aa=', matmul(A,a))

b= [0 1 1]
b.T= [0 1 1]
a•b= 1
b•a= 1
a•b.T= 1
b.T•a= 1
aA= [5 7 9]
Aa= [ 3  9 16]


The shape function returns the shape of an object. Note how my matrices are the expected shape but a and b have a second undefined dimension:

In [19]:
print(shape(A))
print(shape(a))

(3, 3)
(3,)


The solution is to explcitly make my vectors 1xn matrices, which gives the expected behavior:

In [20]:
a = array([[1,1,0]])
b = array([[0,1,1]])

print('a = ',a)
print('b = ',b)
print('a.T = \n',a.T)

a =  [[1 1 0]]
b =  [[0 1 1]]
a.T = 
 [[1]
 [1]
 [0]]


Try some opperations with a b M and A to see that this works better.