In [ ]:
from numpy.linalg import eig, inv, det
from numpy import shape, array, matmul, eye

1) Kinematics Matrix

In [ ]:
A = array([[1,0,0,0],[-1,1,0,0],[0,-1,1,0],[0,0,-1,1],[0,0,0,1]])
print(A)
print('Shape of matrix A:', shape(A))

[[ 1  0  0  0]
 [-1  1  0  0]
 [ 0 -1  1  0]
 [ 0  0 -1  1]
 [ 0  0  0  1]]
Shape of matrix A: (5, 4)


2) Constitutive Matrix

In [ ]:
C = eye(5)
print(C)
print('Shape of matrix C:', shape(C))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape of matrix C: (5, 5)


3) Static Matrix: (Either enter elements or use a matrix operation on an earlier matrix)

In [ ]:
B = -A.T
print(B)
print('Shape of matrix:', shape(B))

[[-1  1  0  0  0]
 [ 0 -1  1  0  0]
 [ 0  0 -1  1  0]
 [ 0  0  0 -1 -1]]
Shape of matrix: (4, 5)


4) Combined Matrix--Use matrix multiplication to find the combined matrix for the equation $\vec{f}=K\vec{x}$

In [ ]:
K = -1*matmul(B,matmul(C,A))
print(K)
print('Shape of matrix:', shape(K))

[[ 2. -1. -0. -0.]
 [-1.  2. -1. -0.]
 [-0. -1.  2. -1.]
 [-0. -0. -1.  2.]]
Shape of matrix: (4, 4)


5) Dynamics: Get the eigenvalus and eigenvectors of the K matrix. 

First try a 2-mass system and compare to the result at 
https://lpsa.swarthmore.edu/MtrxVibe/Anims/VibrationAnimations.html   

In [ ]:
# 2-mass system for comparison

K2 = array([[2,-1],[-1,2]])
w, U = eig(K2)

print("Eigen values w=",w)
print("Eigen vectors:")
print("u1 = ", U[:,0])
print("u2 = ", U[:,1])

Eigen values w= [3. 1.]
Eigen vectors:
u1 =  [ 0.70710678 -0.70710678]
u2 =  [0.70710678 0.70710678]


Now find results for your 4-mass system:

In [ ]:
w, U = eig(K)

print("Eigen values w=",w)
print("Eigen vectors:")
print("u1 = ", U[:,0])
print("u2 = ", U[:,1])

Eigen values w= [3.61803399 2.61803399 0.38196601 1.38196601]
Eigen vectors:
u1 =  [-0.37174803  0.60150096 -0.60150096  0.37174803]
u2 =  [-0.60150096  0.37174803  0.37174803 -0.60150096]


In [ ]:
print(matmul(K,U[:,0])/w[0])

[-0.37174803  0.60150096 -0.60150096  0.37174803]


In [ ]:
help(eig)

Help on function eig in module numpy.linalg:

eig(a)
    Compute the eigenvalues and right eigenvectors of a square array.
    
    Parameters
    ----------
    a : (..., M, M) array
        Matrices for which the eigenvalues and right eigenvectors will
        be computed
    
    Returns
    -------
    w : (..., M) array
        The eigenvalues, each repeated according to its multiplicity.
        The eigenvalues are not necessarily ordered. The resulting
        array will be of complex type, unless the imaginary part is
        zero in which case it will be cast to a real type. When `a`
        is real the resulting eigenvalues will be real (0 imaginary
        part) or occur in conjugate pairs
    
    v : (..., M, M) array
        The normalized (unit "length") eigenvectors, such that the
        column ``v[:,i]`` is the eigenvector corresponding to the
        eigenvalue ``w[i]``.
    
    Raises
    ------
    LinAlgError
        If the eigenvalue computation does not converg